name: easy_card_backend_local

volumes:
  easy_card_db_local_volume:

services:
  flask: &flask
    build:
      context: .
      dockerfile: /docker/local/Dockerfile
    image: easycardapi_local
    container_name: easycardapi_local
    volumes:
      - .:/project
    ports:
      - 5000:5000
    env_file:
      - ./.env
    command: /start
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: easycard_db_local
    restart: always
    env_file:
      - ./.env
    volumes:
      - easy_card_db_local_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
