[tool.poetry]
name = "easycardbackend"
version = "0.1.0"
description = "API for extracting credit card numbers and storing them in the database"
authors = ["Macktireh <abdimack97@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask-migrate = "^4.0.5"
flask-restx = "^1.3.0"
flask-sqlalchemy = "^3.1.1"
numpy = "^1.26.4"
opencv-python = "^4.9.0.80"
psycopg2-binary = "^2.9.9"
pytesseract = "^0.3.10"
python-dotenv = "^1.0.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
