#!/bin/bash

# Error flags configuration for bash
set -o errexit
set -o pipefail
set -o nounset

# Launching migrations and the server
python3 -m flask db upgrade
python3 -m flask run --host=0.0.0.0 --port=5000