"""empty message

Revision ID: abd8f9ce11ee
Revises:
Create Date: 2024-03-06 23:09:05.180750

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "abd8f9ce11ee"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column(
            "type",
            sa.Enum("CARD_500", "CARD_1000", "CARD_2000", "CARD_5000", "CARD_10000", name="typeenum"),
            nullable=False,
        ),
        sa.Column("isValid", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("isActive", sa.Boolean(), nullable=False),
        sa.Column("isAdmin", sa.Boolean(), nullable=False),
        sa.Column("passwordHash", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("cards")
    # ### end Alembic commands ###
