name: Create and publish a Docker image

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  HEALTH_CHECK_URL: http://localhost:5000/health-check
  HEALTH_CHECK_TIMEOUT: 10

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            ${{ github.event.release.prerelease == true && 'type=raw,value=pre-release' || 'type=raw,value=latest' }}

      - name: Build Docker image without push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/production/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}

      - name: Run Docker container
        run: |
          IMAGE_TAGS=$(echo "${{ steps.meta.outputs.tags }}" | cut -d ' ' -f1 | xargs)
          IMAGE_TAG=$(echo "$IMAGE_TAGS" | cut -d ' ' -f1 | xargs)
          echo "Image tag to test: $IMAGE_TAG"
          docker run -d --name easycardbackendtest -p 5000:5000 $IMAGE_TAG
          sleep ${{ env.HEALTH_CHECK_TIMEOUT }}

      - name: Health Check
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.HEALTH_CHECK_URL }})
          echo "Health Check Status: $STATUS"
          if [ $STATUS -ne 200 ]; then
            echo "❌ Health check failed"
            docker logs easycardbackendtest
            exit 1
          fi
          echo "✅ Health check passed"

      - name: Stop Docker container
        run: docker stop easycardbackendtest

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/production/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
